server:
  port: 8089

mybatis:
 #设置实体类别名
 type-aliases-package: com.uiauto.entity
 #mapper文件的路径
 mapper-locations: classpath:mapper/*.xml
 configuration:
   #mybatis开启驼峰转化
   map-underscore-to-camel-case: true
   #mybatis开启二级缓存
   cache-enabled: true
   #使用jdbc的getGeneratedKeys获取数据库自增主键值
   #use-generated-keys: true
   #使用列别名替换列名
   use-column-label: true
   #mybatis的配置
   #config-location: classpath:mybatis-config.xml
   #开启控制台打印sql日志
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
 datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver: com.mysql.cj.jdbc.Driver
      ######数据库名、用户名和密码稍后替换######
      url:  jdbc:mysql://localhost:3306/auto_test?characterEncoding=utf8&useSSL=false&serverZone=UTC&rewriteBatchedStatements=true
      username: root
      password: dansmile3205
      #下面为连接池的补充设置，应用到上面所有数据源中
      #初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      #检测连接是否有，有效得select语句
      validation-query: SELECT 1 FROM DUAL
      #申请连接的时候检测，如果空闲时间大于time-between-eviction-runs-millis，执行validationQuery检测连接是否有效，建议配置为true，不影响性能，并且保证安全性。
      test-while-idle: true
      #申请连接时执行validationQuery检测连接是否有效，建议设置为false，不然会会降低性能
      test-on-borrow: false
      #归还连接时执行validationQuery检测连接是否有效，建议设置为false，不然会会降低性能
      test-on-return: false
      #是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
      pool-prepared-statements: true
      #打开PSCache，并且指定每个连接上PSCache的大小
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      #配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙防御sql注入，stat监控统计,logback日志
      filter:
        commons-log:
          connection-logger-name: stat,wall,log4j
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
      #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      #Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: com.uiauto.service.*,com.uiauto.serviceimpl.*
      web-stat-filter:
        #WebStatFilter监控配置
        enabled: true
        #添加过滤规则：那些访问拦截统计
        url-pattern: /*
 #redis配置
 redis:
   database: 0
   host: 127.0.0.1
   port: 6379
   jedis:
     pool:
       max-idle: 10 # 连接池中的最大空闲连接
       max-active: 200 #连接池最大连接数（使用负值表示没有限制）
       min-idle: 0 #连接池中的最小空闲连接
       max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
   timeout: 6000 #连接超时时间（毫秒）

#rabbitmq配置
 rabbitmq:
   host: 127.0.0.1
   port: 5672
   username: XXXXX
   password: XXXXX

#热部署配置（或者使用JRebel）
 devtools:
   restart:
     enabled: true #开启热部署
     additional-paths: src/main/java
     exclude: static/**

 # 页面修改后立即生效，关闭缓存，立即刷新
 thymeleaf:
   cache: false

 freemarker:
   cache: false



