server:
  port: 8089

mybatis:
 #设置实体类别名
 type-aliases-package: com.interfaceautomationplatform.automation.entity
 #mapper文件的路径
 mapper-locations: classpath:mapper/*.xml
 configuration:
   #mybatis开启驼峰转化
   map-underscore-to-camel-case: true
   #mybatis开启二级缓存
   cache-enabled: true
   #使用jdbc的getGeneratedKeys获取数据库自增主键值
   #use-generated-keys: true
   #使用列别名替换列名
   use-column-label: true
   #mybatis的配置
   #config-location: classpath:mybatis-config.xml
   #开启控制台打印sql日志
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#redis配置

spring:
 datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver: com.mysql.cj.jdbc.Driver
      url:  jdbc:mysql://localhost:3306/auto_test?characterEncoding=utf8&useSSL=false&serverZone=UTC&rewriteBatchedStatements=true
      username: root
      password: dansmile3205
      #下面为连接池的补充设置，应用到上面所有数据源中
      #初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter:
        commons-log:
          connection-logger-name: stat,wall,log4j
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
      #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true


